print("Java - SI")
print("------------------------")
print("JavaScript")
print("------------------------")
print("Python - SI")
print("------------------------")
print("C#"
print("------------------------")
print("C++")
print("------------------------")
print("Ruby")